package cn.aifei.demo.common.db.base;

import java.util.*;
import cn.aifei.db.core.*;
import cn.aifei.db.generator.Table;
import cn.aifei.demo.common.db.model.Task;
import cn.aifei.demo.common.db.dao.TaskDao;

/**
 * Generated by Aifei. Do not edit manually.
 */
@SuppressWarnings("unchecked")
public abstract class BaseTask<T extends BaseTask<T>> extends AifeiRow<T> {

    public static final Table TABLE = new Table(
            "task",
            "id,title,done,created",
            new String[]{"id"},
            Task.class,
            fieldTypeMap()
    );

    private static Map<String, Class<?>> fieldTypeMap() {
        Map<String, Class<?>> map = new LinkedHashMap<>();
        map.put("id", Integer.class);
        map.put("title", String.class);
        map.put("done", Boolean.class);
        map.put("created", java.util.Date.class);
        return map;
    }

    // --------------------------------------------------------------------------------

    public BaseTask() {
        this.table = TABLE.name;
        this.primaryKey = TABLE.primaryKey;
    }

    @Override
    public Class<?> fieldType(String field) {
        return TABLE.fieldTypeMap.get(field);
    }

    @Override
    public boolean columnDefined(String field) {
        return TABLE.fieldTypeMap.containsKey(field);
    }

    // --------------------------------------------------------------------------------

    public static Task of(Integer id) {
        return new Task().put(TABLE.primaryKey[0], id);
    }

    public static TaskDao dao() {
        return new TaskDao();
    }

    // short setters ------------------------------------------------------------------

    public T id(Integer id) {
        return set("id", id);
    }

    /**
     * 标题
     */
    public T title(String title) {
        return set("title", title);
    }

    /**
     * 是否已完成
     */
    public T done(Boolean done) {
        return set("done", done);
    }

    /**
     * 创建时间
     */
    public T created(java.util.Date created) {
        return set("created", created);
    }

    // getters setters ----------------------------------------------------------------

    public Integer getId() {
        return getInt("id");
    }

    public void setId(Integer id) {
        set("id", id);
    }

    /**
     * 标题
     */
    public String getTitle() {
        return getStr("title");
    }

    /**
     * 标题
     */
    public void setTitle(String title) {
        set("title", title);
    }

    /**
     * 是否已完成
     */
    public Boolean getDone() {
        return getBoolean("done");
    }

    /**
     * 是否已完成
     */
    public void setDone(Boolean done) {
        set("done", done);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreated() {
        return getDate("created");
    }

    /**
     * 创建时间
     */
    public void setCreated(java.util.Date created) {
        set("created", created);
    }

    // CRUD ---------------------------------------------------------------------------

    public T insert() {
        return (T) dao().insert((Task) this);
    }

    public T insertOrUpdate() {
        return (T) dao().insertOrUpdate((Task) this);
    }

    public boolean delete() {
        return dao().delete((Task) this);
    }

    public static boolean deleteById(Integer id) {
        return dao().deleteById(id);
    }

    public static int deleteBy(String whereOrField, Object... paraArray) {
        return dao().deleteBy(whereOrField, paraArray);
    }

    public static int deleteInIds(Collection<?> ids) {
        return dao().deleteInIds(ids);
    }

    public static int deleteInIds(Object... idValues) {
        return dao().deleteInIds(idValues);
    }

    public boolean update() {
        return dao().update((Task) this);
    }

    public static TaskDao sql(String sql, Object... paras) {
        return dao().sql(sql, paras);
    }

    public static TaskDao sql(String sql) {
        return dao().sql(sql);
    }

    public static TaskDao sql(String sql, Map<?, ?> data) {
        return dao().sql(sql, data);
    }

    public static TaskDao sqlById(String sqlId, Object... paras) {
        return dao().sqlById(sqlId, paras);
    }

    public static TaskDao sqlById(String sqlId) {
        return dao().sqlById(sqlId);
    }

    public static TaskDao sqlById(String sqlId, Map<?, ?> data) {
        return dao().sqlById(sqlId, data);
    }

    public static TaskDao select(String fields) {
        return dao().select(fields);
    }

    public static Task findById(Integer id) {
        return dao().findById(id);
    }

    public static List<Task> findBy(String whereOrField, Object... paraArray) {
        return dao().findBy(whereOrField, paraArray);
    }

    public static Task findFirstBy(String whereOrField, Object... paraArray) {
        return dao().findFirstBy(whereOrField, paraArray);
    }

    public static List<Task> findInIds(Collection<?> ids) {
        return dao().findInIds(ids);
    }

    public static List<Task> findInIds(Object... idValues) {
        return dao().findInIds(idValues);
    }

    public static long count() {
        return dao().count();
    }

    public static long countBy(String whereOrField, Object... paraArray) {
        return dao().countBy(whereOrField, paraArray);
    }
}



