package cn.aifei.demo.common.db.model;

import cn.aifei.demo.common.db.base.BaseTask;

/**
 * Generated by Aifei.
 * <br>
 * 重新生成不会覆盖此文件，所以支持功能扩展。例如添加此 model 状态判断逻辑。
 */
public class Task extends BaseTask<Task> {

}


