package cn.aifei.demo.common.db;

import java.util.LinkedHashSet;
import cn.aifei.db.core.AifeiRow;
import cn.aifei.demo.common.db.model.*;

/**
 * Generated by Aifei. Do not edit manually.
 */
public class ModelSet extends LinkedHashSet<Class<? extends AifeiRow<?>>> {
    {
        add(Task.class);
    }
}


