package cn.aifei.demo.common.db.dao;

import cn.aifei.db.generator.BaseDao;
import cn.aifei.demo.common.db.model.Task;

/**
 * Generated by Aifei.
 * <br>
 * 注意：Dao 层具有状态，所以不能多线程共享，也不能 Inject 注入 Dao 层。
 *
 * <pre>
 * 重新生成不会覆盖此文件，所以支持功能扩展。例如针对业务添加具体的查询方法，例如覆盖父类相关方法扩展新功能。
 *
 * 例子：
 *   public User findById(Integer id) {
 *       User ret = cache.get("user:" + id);
 *       if (ret == null) {
 *           ret = super.findById(id);
 *           cache.put("user:" + id, ret);
 *       }
 *       return ret;
 *   }
 *
 *  以上代码通过在 UserDao 中添加覆盖父类的 findById 方法，实现了优先从缓存中获取数据的功能
 * </pre>
 */
public class TaskDao extends BaseDao<TaskDao, Task> {
    public TaskDao() {
        super(Task.TABLE);
    }
}


